---
- name: install repo
  yum: name=epel-release state=installed

- name: install nginx
  yum: name=nginx state=installed

- name: update main nginx config file
  template:
    src: "templates/nginx.conf"
    dest: "/etc/nginx/nginx.conf"
    backup: yes
  notify:
    - check configuration
    - reload nginx
    - check port

