---
- name: install repo
  yum: name=epel-release state=installed

- name: install nginx
  yum: name=nginx state=installed

- name: enable nginx service
  service: name=nginx state=started

- name: start nginx service
  service: name=nginx enabled=yes 

- name: check nginx running and enabled
  service: name=nginx state=started enabled=yes

- name: check port 80 answering
  wait_for: port=80