---
- name: install repo
  yum: name=epel-release state=installed

- name: install nginx
  yum: name=nginx state=installed

- name: Create main nginx config file
  template:
    src: "templates/nginx.conf"
    dest: "/etc/nginx/nginx.conf"
    backup: yes

- name: check nginx running and enabled
  service: name=nginx state=restarted enabled=yes

- name: check port {{ nginx_port }} answering
  wait_for: port={{ nginx_port }}
