---

- name: update main nginx config file
  template:
    src: "templates/nginx.conf"
    dest: "/etc/nginx/nginx.conf"
    backup: yes
  notify:
    - check syntax
    - reload nginx
    - check port

